#!/bin/bash
# ==============================================================
# 02_services_install.sh — Core service installation
# ==============================================================

set -e
echo "==> Installing core server services..."

# --- Sunshine (game streaming) ---
echo "==> Installing Sunshine..."
mkdir -p /opt/sunshine && cd /opt/sunshine
SUN_VER=$(curl -s https://api.github.com/repos/LizardByte/Sunshine/releases/latest | grep "tag_name" | cut -d '"' -f 4)
wget -O sunshine.deb "https://github.com/LizardByte/Sunshine/releases/download/$SUN_VER/sunshine-${SUN_VER}-amd64.deb"
apt install -y ./sunshine-${SUN_VER}-amd64.deb
systemctl enable sunshine

# --- Ollama (AI inference engine) ---
echo "==> Installing Ollama..."
curl -fsSL https://ollama.com/download.sh | sh
systemctl enable ollama

# --- qBittorrent-nox (headless client) ---
echo "==> Installing qBittorrent..."
apt install -y qbittorrent-nox
useradd -r -m -U -d /var/lib/qbittorrent -s /usr/sbin/nologin qbittorrent || true

cat <<'EOF' >/etc/systemd/system/qbittorrent.service
[Unit]
Description=qBittorrent Headless Service
After=network.target

[Service]
User=qbittorrent
ExecStart=/usr/bin/qbittorrent-nox --webui-port=8080
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable qbittorrent

# --- No-IP Dynamic DNS client ---
echo "==> Installing No-IP DUC..."
apt install -y make gcc
cd /usr/local/src
wget -q https://www.noip.com/client/linux/noip-duc-linux.tar.gz
tar xf noip-duc-linux.tar.gz
cd noip-2.1.9*
make install

cat <<EOF >/usr/local/etc/no-ip2.conf
# Autogenerated No-IP configuration
USER=pzv71v
PASSWORD=1VfAKTa7TxYZ
HOST=all.ddnskey.com
INTERVAL=30
EOF

cat <<'EOF' >/etc/systemd/system/noip2.service
[Unit]
Description=No-IP Dynamic DNS Update Client
After=network.target

[Service]
ExecStart=/usr/local/bin/noip2
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable noip2.service

# --- Media stack (Jellyfin, FFmpeg, Samba, NFS) ---
echo "==> Installing media services..."
apt install -y jellyfin ffmpeg samba nfs-common vlc

# Samba share for media
cat <<'EOF' >>/etc/samba/smb.conf

[Media]
path = /srv/media
browsable = yes
writable = yes
guest ok = yes
read only = no
create mask = 0777
directory mask = 0777
EOF

mkdir -p /srv/media
chmod 777 /srv/media
systemctl restart smbd nmbd

# --- Create AI model storage directory ---
mkdir -p /srv/llm_models
chown gp:gp /srv/llm_models

# --- Network tuning for Mellanox NIC ---
IFACE=$(ls /sys/class/net | grep -m1 enp || true)
if [ -n "$IFACE" ]; then
  ethtool -G "$IFACE" rx 4096 tx 4096 || true
  ethtool -K "$IFACE" gro on gso on tso on rx on tx on || true
fi

# --- Cleanup ---
apt autoremove -y && apt clean

echo "==> Core services installation complete. Proceed to 03_monitoring_setup.sh."
